version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 148097737392.dkr.ecr.ap-northeast-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm run build
      - TAG=`date +%Y%m%d%H%M%S`
      - echo $TAG > imageTag.txt
      - docker build -t 148097737392.dkr.ecr.ap-northeast-1.amazonaws.com/my-ecr-2025:$TAG .
      - docker push 148097737392.dkr.ecr.ap-northeast-1.amazonaws.com/my-ecr-2025:$TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - TAG=$(cat imageTag.txt)
      - echo '{}' | jq --arg name "mynginx" --arg uri "148097737392.dkr.ecr.ap-northeast-1.amazonaws.com/my-ecr-2025:$TAG" '[{name: $name, imageUri: $uri}]' > imageDefinitions.json
      - echo "==== imageDefinitions.json 内容 ===="
      - cat imageDefinitions.json
      - echo "==== 查看是否存在隐藏字符 ===="
      - od -c imageDefinitions.json
      - echo "==== 当前目录下的文件列表 ===="
      - ls -lh

artifacts:
  files:
    - imageDefinitions.json
    - imageTag.txt
